DEF NUM_PLAYER_NAMES EQU 3

DEF PLAYERNAME1 EQUS "RED"
DEF PLAYERNAME2 EQUS "ASH"
DEF PLAYERNAME3 EQUS "CHASE"

DEF RIVALNAME1 EQUS "BLUE"
DEF RIVALNAME2 EQUS "GARY"
DEF RIVALNAME3 EQUS "TRACE"

DEF FRIENDNAME1 EQUS "GREEN"
DEF FRIENDNAME2 EQUS "LEAF"
DEF FRIENDNAME3 EQUS "ELAINE"



